<a href="https://colab.research.google.com/github/chughtaiahmad4002-dev/Project_Webscrapping_with_Pandas.ipynb/blob/main/Project_Webscrapping_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

# 1) Read file from URL with **pandas**

In [25]:
#Read 1 file from the website
df_country = pd.read_html("https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population", storage_options={'User-Agent': 'Mozilla/5.0'})

In [26]:
#showing dataframe
df_country[0]

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[248],NaN
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[249],NaN
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[250],[ah]
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[251],NaN
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[252],NaN

In [27]:
#rename the columns
df_country[0].rename(columns={"% of world":"Percentage of World","Source (official or from the United Nations)":"Reference (official or from the United Nations)"},inplace=True)

In [30]:
#showing DataFrame
df_country[0]

,Location,Population,Percentage of World,Date,Reference (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[248],NaN
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[249],NaN
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[250],[ah]
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[251],NaN
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[252],NaN

# 2) Read multiple files from multiple URLs with pandas and add a column

In [69]:
import pandas as pd

# List of URLs containing tables
urls = [
    "https://en.wikipedia.org/wiki/List_of_continents_by_population",
    "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population",
]

headers = {"User-Agent": "Mozilla/5.0"}

# 1. Create an empty list to store our DataFrames
dataframes = []

# 2. Use for loop to iterate through each URL
for url in urls:
    # Read all tables from the URL and grab the first one ([0])
    df = pd.read_html(url, storage_options=headers)[0]
    # Adding a new column
    df['Source'] = url
    # Append (add) this DataFrame to our list
    dataframes.append(df)

In [73]:
dataframes[0]

,0,1,2,3,4,5,6,7,Source
0,Continental landmass,Population (2021)[1][2][3],% (world),±% p.a. (2010–2013),Sovereign states (2025),De facto states (2025),Non-self-governing territories (2025),Other area(s) (2025),https://en.wikipedia.org/wiki/List_of_continen...
1,World,7909295151,100%,1.17%,197,8,17,34,https://en.wikipedia.org/wiki/List_of_continen...
2,Afro-Eurasia,6833426385,86.4%,86.4%,146,8,3,12,https://en.wikipedia.org/wiki/List_of_continen...
3,America,1030037584,13%,0.96%,35,0,8,14,https://en.wikipedia.org/wiki/List_of_continen...
4,Oceania[a],44491724,0.6%,1.47%,16,0,6,7,https://en.wikipedia.org/wiki/List_of_continen...
5,Antarctica,0,0%,0%,0,0,0,1,https://en.wikipedia.org/wiki/List_of_continen...

In [77]:
dataframes[1]

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes,Source
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b],https://en.wikipedia.org/wiki/List_of_countrie...
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c],https://en.wikipedia.org/wiki/List_of_countrie...
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d],https://en.wikipedia.org/wiki/List_of_countrie...
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
...,...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[248],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[249],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[250],[ah],https://en.wikipedia.org/wiki/List_of_countrie...
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[251],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[252],NaN,https://en.wikipedia.org/wiki/List_of_countrie...

# 3) Organize all the Data in a Dictionary

In [74]:
dict_world={
    "Continents":dataframes[0],
    "Countries":dataframes[1]
}

In [75]:
dict_world["Continents"]

,0,1,2,3,4,5,6,7,Source
0,Continental landmass,Population (2021)[1][2][3],% (world),±% p.a. (2010–2013),Sovereign states (2025),De facto states (2025),Non-self-governing territories (2025),Other area(s) (2025),https://en.wikipedia.org/wiki/List_of_continen...
1,World,7909295151,100%,1.17%,197,8,17,34,https://en.wikipedia.org/wiki/List_of_continen...
2,Afro-Eurasia,6833426385,86.4%,86.4%,146,8,3,12,https://en.wikipedia.org/wiki/List_of_continen...
3,America,1030037584,13%,0.96%,35,0,8,14,https://en.wikipedia.org/wiki/List_of_continen...
4,Oceania[a],44491724,0.6%,1.47%,16,0,6,7,https://en.wikipedia.org/wiki/List_of_continen...
5,Antarctica,0,0%,0%,0,0,0,1,https://en.wikipedia.org/wiki/List_of_continen...

In [76]:
dict_world["Countries"]

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes,Source
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b],https://en.wikipedia.org/wiki/List_of_countrie...
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c],https://en.wikipedia.org/wiki/List_of_countrie...
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d],https://en.wikipedia.org/wiki/List_of_countrie...
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
...,...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[248],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[249],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[250],[ah],https://en.wikipedia.org/wiki/List_of_countrie...
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[251],NaN,https://en.wikipedia.org/wiki/List_of_countrie...
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[252],NaN,https://en.wikipedia.org/wiki/List_of_countrie...

#Project webscraping with pandas is Finished