<a href="https://colab.research.google.com/github/chughtaiahmad4002-dev/Data_preprocessing_with_Pandas.ipynb/blob/main/Webscraping_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

# 1) Read file from URL with **pandas**

In [4]:
#Read file from the website
# 1) Scrape Continents Data from its specific URL
continents_url = "https://en.wikipedia.org/wiki/List_of_continents_by_population"
df_continents = pd.read_html(continents_url, storage_options={'User-Agent': 'Mozilla/5.0'})[0]

# 2) Scrape Countries Data from its specific URL
countries_url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"
df_countries = pd.read_html(countries_url, storage_options={'User-Agent': 'Mozilla/5.0'})[0]

In [10]:
#showing dataframe
df_continents

,0,1,2,3,4,5,6,7
0,Continental landmass,Population (2021)[1][2][3],% (world),±% p.a. (2010–2013),Sovereign states (2025),De facto states (2025),Non-self-governing territories (2025),Other area(s) (2025)
1,World,7909295151,100%,1.17%,197,8,17,34
2,Afro-Eurasia,6833426385,86.4%,1.25%,146,8,3,12
3,America,1030037584,13%,0.96%,35,0,8,14
4,Oceania[a],44491724,0.6%,1.47%,16,0,6,7
5,Antarctica,0,0%,0%,0,0,0,1

In [9]:
#showing dataframe
df_countries

,Location,Population,% of world,Date,Source (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[247],NaN
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[248],NaN
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[249],[ah]
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[250],NaN
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[251],NaN

In [13]:
#rename the columns
df_countries.rename(columns={"% of world":"Percentage of World","Source (official or from the United Nations)":"Reference (official or from the United Nations)"},inplace=True)

In [15]:
#showing DataFrame
df_countries

,Location,Population,Percentage of World,Date,Reference (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[247],NaN
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[248],NaN
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[249],[ah]
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[250],NaN
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[251],NaN

# 2) Read multiple files from multiple URLs with pandas and add a column

In [16]:
def run_scraping_pipeline(url):
    """
    Automated pipeline that extracts a Wikipedia table,
    cleans column names, and exports a ready-to-use CSV file.
    """
    print("Step 1: Extracting data from web...")
    dfs = pd.read_html(url, storage_options={'User-Agent': 'Mozilla/5.0'})
    df = dfs[0]

    print("Step 2: Cleaning and standardizing column names...")
    df = df.rename(columns={
        "% of world": "Percentage of World",
        "Source (official or from the United Nations)": "Reference (official or from the United Nations)"
    })

    df = df.dropna(how='all')

    print("Step 3: Exporting processed dataset...")
    output_filename = "cleaned_population_pipeline_output.csv"
    df.to_csv(output_filename, index=False)

    print(f"Pipeline complete! Saved file as: {output_filename}")
    return df

# --- Execute the Pipeline ---
target_url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population"
pipeline_df = run_scraping_pipeline(target_url)

Step 1: Extracting data from web...
Step 2: Cleaning and standardizing column names...
Step 3: Exporting processed dataset...
Pipeline complete! Saved file as: cleaned_population_pipeline_output.csv

In [17]:
df_countries

,Location,Population,Percentage of World,Date,Reference (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[247],NaN
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[248],NaN
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[249],[ah]
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[250],NaN
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[251],NaN

In [22]:
df_continents

,0,1,2,3,4,5,6,7
0,Continental landmass,Population (2021)[1][2][3],% (world),±% p.a. (2010–2013),Sovereign states (2025),De facto states (2025),Non-self-governing territories (2025),Other area(s) (2025)
1,World,7909295151,100%,1.17%,197,8,17,34
2,Afro-Eurasia,6833426385,86.4%,1.25%,146,8,3,12
3,America,1030037584,13%,0.96%,35,0,8,14
4,Oceania[a],44491724,0.6%,1.47%,16,0,6,7
5,Antarctica,0,0%,0%,0,0,0,1

# 3) Organize all the Data in a Dictionary

In [19]:
dict_world={
    "Continents":df_continents,
    "Countries":df_countries
}

In [20]:
dict_world["Continents"]

,0,1,2,3,4,5,6,7
0,Continental landmass,Population (2021)[1][2][3],% (world),±% p.a. (2010–2013),Sovereign states (2025),De facto states (2025),Non-self-governing territories (2025),Other area(s) (2025)
1,World,7909295151,100%,1.17%,197,8,17,34
2,Afro-Eurasia,6833426385,86.4%,1.25%,146,8,3,12
3,America,1030037584,13%,0.96%,35,0,8,14
4,Oceania[a],44491724,0.6%,1.47%,16,0,6,7
5,Antarctica,0,0%,0%,0,0,0,1

In [21]:
dict_world["Countries"]

,Location,Population,Percentage of World,Date,Reference (official or from the United Nations),Notes
0,World,8.232000e+09,100%,13 Jun 2025,UN projection[1][3],NaN
1,India,1.429404e+09,17.3%,1 Jul 2026,Official projection[4],[b]
2,China,1.404890e+09,17.0%,31 Dec 2025,Official estimate[5],[c]
3,United States,3.417849e+08,4.1%,1 Jul 2025,Official estimate[6],[d]
4,Indonesia,2.883151e+08,3.5%,31 Dec 2025,National annual projection[7],NaN
...,...,...,...,...,...,...
236,Christmas Island (Australia),1.692000e+03,0%,1 Jan 2021,2021 Census[247],NaN
237,Niue (New Zealand),1.681000e+03,0%,11 Nov 2022,2022 Census[248],NaN
238,Vatican City,8.820000e+02,0%,31 Dec 2024,Official figure[249],[ah]
239,Cocos (Keeling) Islands (Australia),5.930000e+02,0%,30 Jun 2020,2021 Census[250],NaN
240,Pitcairn Islands (UK),3.500000e+01,0%,2023,Official estimate[251],NaN

#Project webscraping with pandas is Finished